[project]
name = "fastapi-microservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">= 3.13"
dependencies = [
    "fastapi[standard] >= 0.95.0",
    "uvicorn >= 0.22.0",
]
